"""
MindSpore 训练模板生成器
========================

根据配置生成完整的训练脚本。
"""

from __future__ import annotations
from typing import Any


def generate_training_script(
    task: str = "image_classification",
    model: str = "resnet50",
    dataset: str = "cifar10",
    hardware: str = "Ascend",
    num_epochs: int = 90,
    batch_size: int = 32,
    base_lr: float = 0.001,
    optimizer: str = "adam",
    lr_scheduler: str = "cosine",
    use_amp: bool = True,
    seed: int = 42,
) -> dict[str, Any]:
    """生成 MindSpore 训练脚本

    根据任务类型、模型、数据集等参数，生成完整可运行的训练脚本。
    复用现有 msutils 工具的配置。

    Args:
        task: 任务类型
            - "image_classification": 图像分类
            - "object_detection": 目标检测
            - "nlp": NLP 任务
        model: 模型名称
            - "resnet18", "resnet34", "resnet50", "resnet101"
            - "lenet": LeNet
        dataset: 数据集名称
            - "cifar10", "cifar100", "imagenet"
        hardware: 硬件平台
            - "Ascend": 华为昇腾
            - "GPU": NVIDIA GPU
            - "CPU": CPU
        num_epochs: 训练轮数
        batch_size: 批次大小
        base_lr: 基础学习率
        optimizer: 优化器类型 ("adam", "sgd", "adamw")
        lr_scheduler: 学习率调度器 ("cosine", "step", "none")
        use_amp: 是否使用混合精度训练
        seed: 随机种子

    Returns:
        {
            "script": "完整训练脚本代码",
            "filename": "train_image_classification_resnet50.py",
            "config": {...配置摘要...},
            "description": "脚本说明"
        }

    Examples:
        >>> result = generate_training_script(
        ...     task="image_classification",
        ...     model="resnet50",
        ...     dataset="cifar10",
        ...     hardware="Ascend"
        ... )
        >>> print(result["filename"])
        train_image_classification_resnet50.py
        >>> print(result["script"][:500])
    """
    import datetime
    
    # 任务配置
    task_configs = {
        "image_classification": {
            "dataset_api": "Cifar10Dataset",
            "num_classes": 10,
            "img_size": 224,
            "feature_size": 7,
            "loss_fn": "CrossEntropyLoss",
        },
        "object_detection": {
            "dataset_api": "COCOObjectDetectionDataset",
            "num_classes": 80,
            "img_size": 640,
            "feature_size": 20,
            "loss_fn": "SampledSoftmaxLoss",
        },
        "nlp": {
            "dataset_api": "NLP Dataset",
            "num_classes": 2,
            "img_size": 512,
            "feature_size": None,
            "loss_fn": "CrossEntropyLoss",
        },
    }
    
    config = task_configs.get(task, task_configs["image_classification"])
    hw_target = hardware.capitalize()
    amp_level = "O3" if hardware == "Ascend" else "O2" if hardware == "GPU" else "O0"
    use_amp = use_amp and hardware != "CPU"
    
    # 生成脚本
    script_parts = []
    
    # === 头部 ===
    script_parts.append(f'''#!/usr/bin/env python3
"""
{task.replace("_", " ").title()} Training Script
{'=' * 50}

Generated by mindspore-tools-mcp Training Template Generator

配置信息:
- 任务: {task}
- 模型: {model}
- 数据集: {dataset}
- 硬件: {hardware}
- 训练轮数: {num_epochs}
- 批次大小: {batch_size}
- 学习率: {base_lr}
- 优化器: {optimizer}
- 学习率调度: {lr_scheduler}
- 混合精度: {use_amp}

生成时间: {datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S")}
"""

import mindspore as ms
from mindspore import nn
from mindspore.dataset import vision, transforms
import os
import time
''')

    # === 数据加载 ===
    script_parts.append('''
# =============================================================================
# 数据加载
# =============================================================================

def create_dataset(data_path: str, batch_size: int = 32, train: bool = True, num_workers: int = 4):
    """创建数据集"""
    import mindspore.dataset as ds
    
    transform_list = [
        vision.RandomCrop({img_size}, padding=4) if train else vision.CenterCrop({img_size}),
        vision.RandomHorizontalFlip() if train else vision.CenterCrop({img_size}),
        vision.Resize({img_size}),
        vision.Div(255.0),
        vision.Normalize(mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225]),
    ]
    
    dataset = ds.{dataset_api}(
        data_path,
        num_shards=None,
        shard_id=None,
        shuffle=train,
        num_parallel_workers=num_workers,
    )
    
    typecast_op = transforms.TypeCast("int32")
    
    dataset = dataset.map(operations=transform_list, input_columns="image", num_parallel_workers=num_workers)
    dataset = dataset.map(operations=typecast_op, input_columns="label", num_parallel_workers=num_workers)
    dataset = dataset.batch(batch_size, drop_remainder=train)
    
    return dataset
'''.format(
        img_size=config["img_size"],
        dataset_api=config["dataset_api"]
    ))

    # === 模型定义 ===
    script_parts.append(f'''
# =============================================================================
# 模型定义
# =============================================================================

def create_model(model_name: str, num_classes: int = {config["num_classes"]}) -> nn.Cell:
    """创建模型"""
    from mindspore.model_zoo import resnet
    
    model_name = model_name.lower()
    
    if model_name == "resnet18":
        return resnet.resnet18(num_classes=num_classes)
    elif model_name == "resnet34":
        return resnet.resnet34(num_classes=num_classes)
    elif model_name == "resnet50":
        return resnet.resnet50(num_classes=num_classes)
    elif model_name == "resnet101":
        return resnet.resnet101(num_classes=num_classes)
    elif "lenet" in model_name:
        return nn.SequentialCell([
            nn.Conv2d(3, 6, 5, pad_mode="valid"),
            nn.ReLU(),
            nn.MaxPool2d(kernel_size=2, stride=2),
            nn.Conv2d(6, 16, 5, pad_mode="valid"),
            nn.ReLU(),
            nn.MaxPool2d(kernel_size=2, stride=2),
            nn.Flatten(),
            nn.Dense(400, 120),
            nn.ReLU(),
            nn.Dense(120, 84),
            nn.ReLU(),
            nn.Dense(84, num_classes),
        ])
    else:
        # 默认简单 CNN
        return nn.SequentialCell([
            nn.Conv2d(3, 32, 3, pad_mode="pad", padding=1),
            nn.ReLU(),
            nn.MaxPool2d(kernel_size=2, stride=2),
            nn.Conv2d(32, 64, 3, pad_mode="pad", padding=1),
            nn.ReLU(),
            nn.MaxPool2d(kernel_size=2, stride=2),
            nn.Conv2d(64, 64, 3, pad_mode="pad", padding=1),
            nn.ReLU(),
            nn.Flatten(),
            nn.Dense(64 * 7 * 7, 512),
            nn.ReLU(),
            nn.Dropout(p=0.5),
            nn.Dense(512, num_classes),
        ])
''')

    # === 训练配置 ===
    script_parts.append(f'''
# =============================================================================
# 训练配置
# =============================================================================

# 设置随机种子
ms.set_seed({seed})

# 配置上下文
ms.context.set_context(
    mode=ms.GRAPH_MODE,
    device_target="{hw_target}",
    device_id=int(os.environ.get("DEVICE_ID", 0)),
)

# Ascend 优化
if "{hw_target}" == "Ascend":
    ms.context.set_context(enable_graph_kernel=True)

# 模型
model = create_model("{model}", num_classes={config["num_classes"]})
print(f"Model: {{model.__class__.__name__}}")
print(f"Parameters: {{sum(p.size for p in model.get_parameters()) / 1e6:.2f}}M")
''')

    # === 学习率和优化器 ===
    if lr_scheduler == "cosine":
        lr_code = '''
# 学习率调度 (余弦退火)
from mindspore.experimental.optim import lr_scheduler

total_steps = num_epochs * train_dataset.get_dataset_size()
warmup_steps = total_steps // 10

lr_scheduler = lr_scheduler.cosine_decay_lr(
    min_lr=1e-6,
    max_lr=base_lr,
    total_steps=total_steps,
    warmup_steps=warmup_steps,
)
'''
    elif lr_scheduler == "step":
        lr_code = '''
# 学习率调度 (阶梯衰减)
lr_scheduler = base_lr
'''
    else:
        lr_code = f'''
# 固定学习率
lr_scheduler = {base_lr}
'''

    opt_configs = {
        "adam": ("Adam", "weight_decay=0.0001"),
        "sgd": ("Momentum", "momentum=0.9, weight_decay=0.0001"),
        "adamw": ("AdamWeightDecay", "weight_decay=0.01"),
    }
    opt_name, opt_extra = opt_configs.get(optimizer.lower(), ("Adam", "weight_decay=0.0001"))

    script_parts.append(f'''
# 学习率
base_lr = {base_lr}
num_epochs = {num_epochs}
{lr_code}

# 优化器
optimizer = nn.{opt_name}(
    params=model.trainable_params(),
    learning_rate=lr_scheduler,
    {opt_extra}
)
''')

    # === 回调函数 ===
    script_parts.append('''
# =============================================================================
# 回调函数
# =============================================================================

from mindspore.train import ModelCheckpoint, CheckpointConfig, EarlyStoppingCallback

# 检查点保存
ckpt_dir = f"./checkpoints/{model_name}"
os.makedirs(ckpt_dir, exist_ok=True)

ckpt_config = CheckpointConfig(
    save_checkpoint_steps=1000,
    keep_checkpoint_max=5,
)
ckpt_callback = ModelCheckpoint(
    prefix=model_name,
    directory=ckpt_dir,
    config=ckpt_config,
)

# 早停
early_stop = EarlyStoppingCallback(
    monitor="val_loss",
    patience=10,
    min_delta=0.001,
    verbose=True,
)

# 进度显示
from mindspore.train.callback import ProgressMonitor
progress_cb = ProgressMonitor(per_print_times=100)

callbacks = [ckpt_callback, early_stop, progress_cb]
''')

    # === 训练循环 ===
    loss_scale_str = "loss_scale_manager=loss_scale_manager," if use_amp else ""
    sink_mode = "True" if hardware != "CPU" else "False"

    script_parts.append(f'''
# =============================================================================
# 训练
# =============================================================================

# 损失函数
loss_fn = nn.{config["loss_fn"]}()

# 数据集
data_path = "./data/{dataset}"
train_dataset = create_dataset(os.path.join(data_path, "train"), batch_size={batch_size}, train=True)
test_dataset = create_dataset(os.path.join(data_path, "test"), batch_size={batch_size}, train=False)

print(f"Train batches: {{train_dataset.get_dataset_size()}}")
print(f"Test batches: {{test_dataset.get_dataset_size()}}")

# 训练网络
train_network = nn.TrainOneStepCell(model, optimizer, loss_fn)

# 评估网络
eval_network = nn.WithEvalCell(model, loss_fn)

# 模型
metrics = {{"accuracy": nn.Accuracy(), "loss": nn.Loss()}}
train_model = ms.train.Model(
    network=train_network,
    eval_network=eval_network,
    metrics=metrics,
    {loss_scale_str}
)

# 开始训练
print("\\n" + "=" * 60)
print("Start Training")
print("=" * 60)

start_time = time.time()

train_model.train(
    {num_epochs},
    train_dataset,
    callbacks=callbacks,
    dataset_sink_mode={sink_mode},
)

end_time = time.time()
print(f"\\nTraining completed in {{end_time - start_time:.2f}} seconds")

# 最终评估
print("\\n" + "=" * 60)
print("Final Evaluation")
print("=" * 60)

result = train_model.eval(test_dataset, dataset_sink_mode=False)
print(f"Test Accuracy: {{result['accuracy']:.4f}}")
print(f"Test Loss: {{result['loss']:.4f}}")

print("\\n" + "=" * 60)
print("Training Complete!")
print("=" * 60)
''')

    # === 主函数入口 ===
    script_parts.append(f'''
# =============================================================================
# 主函数
# =============================================================================

if __name__ == "__main__":
    import argparse
    
    parser = argparse.ArgumentParser(description="MindSpore {task.replace("_", " ").title()} Training")
    parser.add_argument("--data_path", type=str, default="./data/{dataset}", help="Path to dataset")
    parser.add_argument("--batch_size", type=int, default={batch_size}, help="Batch size")
    parser.add_argument("--epochs", type=int, default={num_epochs}, help="Number of epochs")
    parser.add_argument("--lr", type=float, default={base_lr}, help="Learning rate")
    parser.add_argument("--device", type=str, default="{hardware}", help="Device: Ascend/GPU/CPU")
    
    args = parser.parse_args()
    
    print(f"Configuration:")
    print(f"  Dataset: {{args.data_path}}")
    print(f"  Batch Size: {{args.batch_size}}")
    print(f"  Epochs: {{args.epochs}}")
    print(f"  Learning Rate: {{args.lr}}")
    print(f"  Device: {{args.device}}")
''')

    # 组装脚本
    full_script = "\n".join(script_parts)

    return {
        "script": full_script,
        "filename": f"train_{task}_{model}.py",
        "config": {
            "task": task,
            "model": model,
            "dataset": dataset,
            "hardware": hardware,
            "epochs": num_epochs,
            "batch_size": batch_size,
            "learning_rate": base_lr,
            "optimizer": optimizer,
            "lr_scheduler": lr_scheduler,
            "use_amp": use_amp,
        },
        "description": f"生成 {task} 任务的完整训练脚本，使用 {model} 模型在 {dataset} 数据集上训练",
    }


def list_available_models() -> dict[str, list[str]]:
    """获取支持的模型列表

    Returns:
        {
            "resnet": ["resnet18", "resnet34", "resnet50", "resnet101"],
            "custom": ["lenet", "simple_cnn"]
        }
    """
    return {
        "resnet": ["resnet18", "resnet34", "resnet50", "resnet101"],
        "custom": ["lenet", "simple_cnn"],
        "mobilenet": ["mobilenet_v2"],
        "efficientnet": ["efficientnet_b0"],
    }


def list_available_datasets() -> dict[str, dict]:
    """获取支持的数据集列表

    Returns:
        {
            "cifar10": {{"classes": 10, "img_size": 224, "train_samples": 50000}},
            "cifar100": {{"classes": 100, "img_size": 224, "train_samples": 50000}},
            "imagenet": {{"classes": 1000, "img_size": 224, "train_samples": 1281167}}
        }
    """
    return {
        "cifar10": {
            "classes": 10,
            "img_size": 32,
            "train_samples": 50000,
            "test_samples": 10000,
            "description": "CIFAR-10 图像分类数据集",
        },
        "cifar100": {
            "classes": 100,
            "img_size": 32,
            "train_samples": 50000,
            "test_samples": 10000,
            "description": "CIFAR-100 图像分类数据集",
        },
        "imagenet": {
            "classes": 1000,
            "img_size": 224,
            "train_samples": 1281167,
            "test_samples": 50000,
            "description": "ImageNet 图像分类数据集",
        },
    }


def get_template_preview(
    task: str = "image_classification",
    model: str = "resnet50",
) -> dict[str, Any]:
    """获取模板预览（只显示脚本的关键部分）

    Returns:
        {
            "header": "脚本头部信息",
            "key_parts": ["关键代码片段"],
            "total_lines": 预计行数
        }
    """
    preview_script = generate_training_script(
        task=task,
        model=model,
        dataset="cifar10",
        hardware="Ascend",
        num_epochs=90,
        batch_size=32,
        base_lr=0.001,
        optimizer="adam",
        lr_scheduler="cosine",
        use_amp=True,
    )

    lines = preview_script["script"].split("\n")

    return {
        "header": "\n".join(lines[:20]),
        "key_parts": [
            "\n".join(lines[20:50]),   # 数据加载
            "\n".join(lines[50:80]),   # 模型定义
            "\n".join(lines[80:120]),   # 训练配置
            "\n".join(lines[-30:]),     # 主函数
        ],
        "total_lines": len(lines),
        "filename": preview_script["filename"],
    }
